<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d6360b19-9786-439f-aa67-f8ab5508c834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='activity-facilities']/div/div/div/div[11]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s-gk.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit2424gsm/events/2021/08/20/3ee3b837-10ab-49e0-beff-dbf6f2caede5-1629451779759-b976418177ff954f5c1ef26665f95d20.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activity-facilities&quot;)/div[@class=&quot;facility-container&quot;]/div[@class=&quot;checkbox-scroll-container&quot;]/div[@class=&quot;checkbox-container&quot;]/div[@class=&quot;checkbox inline label-right&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='activity-facilities']/div/div/div/div[11]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://s-gk.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit2424gsm/events/2021/08/20/3ee3b837-10ab-49e0-beff-dbf6f2caede5-1629451779759-b976418177ff954f5c1ef26665f95d20.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/img</value>
   </webElementXpaths>
</WebElementEntity>
