<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ubah_icon icon-add-box</name>
   <tag></tag>
   <elementGuidId>7f4e0d01-e51f-45d1-9628-5b893d765708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon.icon-add-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/div[2]/div[4]/div/div[2]/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-add-box</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;layout inner&quot;]/div[@class=&quot;row main&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;inventory-management landing&quot;]/div[@class=&quot;mgmt-inventory-list&quot;]/div[@class=&quot;activity-container&quot;]/div[@class=&quot;list-container&quot;]/div[@class=&quot;product-listing&quot;]/div[@class=&quot;mgmt-inventory-list-product-box is-product&quot;]/div[@class=&quot;package-actions&quot;]/button[@class=&quot;button-with-icon&quot;]/div[@class=&quot;icon icon-add-box&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/div[2]/div[4]/div/div[2]/button/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
   </webElementXpaths>
</WebElementEntity>
